name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup elm
        uses: justgook/setup-elm@v1

      - name: Elm Make
        run: elm make src/Main.elm

      - name: Prepare public
        run: |
          mkdir ./public
          mv ./index.html ./public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          allow_empty_commit: true
